### ISSUE TITLE
Is testing the rules in PHP still a valid thing to do?

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#100]
As per topic, what do people think?
I doubt the new Validator will be using PHP and I'm keen to even re-write the current public validator in Python at some point because we don't really have much expertise around PHP, so might as well just get rid of all the related scripts?

**Comment by andylolz** [comment]
+1 for dropping PHP support! :tada:

**Comment by andylolz** [comment]
I suspect the PHP code only ever existed in order to be used in the (PHP) official validator. That never happened (as we know, the official validator doesn’t support ruleset testing) so I doubt it’s used anywhere.
