### ISSUE TITLE
[2.02] Port new rules fom 2.01 to 2.02

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#112]
Make a diff between `version-2.01` and `version-2.02` branches and verify if it can be merged like that, otherwise highlight differences and a plan.

Hold this issue untill the new rules added in `2.01` have been consolidated

**Comment by andylolz** [comment]
There are a few issues with the new rules on `version-2.01`. I wonder if it would be easier to iron those out first, before updating other branches? Otherwise you’ll have to apply the fixes in more places.

**Comment by samuele-mattiuzzo** [comment]
sorry, didn't include that part as it's a known within the IATI Tech Team, but I keep forgetting we have external people keeping a keen eye on our work :) Initial issue updated.

**Comment by andylolz** [comment]
😞 okay

**Comment by samuele-mattiuzzo** [comment]
ah don't be sad! it's correct to point out that in a public repo the opening issue should be as precise and as descriptive as possible 🍡

**Comment by samuele-mattiuzzo** [comment]
I have no idea what that skewery thing is or how it came to be, i meant to post a smiley face

**Comment by andylolz** [comment]
> in a public repo the opening issue should be as precise and as descriptive as possible

That makes it sound like I’m being extremely pedantic. I wasn’t aiming to be.

I just wanted to be sure that rules won’t be copied across in their current state. I’m pleased that they’ll be fixed first.

**Comment by samuele-mattiuzzo** [comment]
@andylolz we can try to discuss those issues you mention about and see if explaining how/why we implemented them as such makes sense or still needs steering. What have you identified?

/cc @Ocre42

**Comment by andylolz** [comment]
Do you mind if I make separate issues for the issues? Might be clearer.
