### ISSUE TITLE
Add a URL reference to each rule

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#121]
Most of the rules in the ruleset have some relevant documentation on http://reference.iatistandard.org, which could provide further reading for the user, in order to understand the issue. In fact, the spec for the new validator says it should:

> Provide a link to the Standard’s page related to an issue

In order to do this, it would be handy if these links could be provided in standard.json, alongside each rule. Even better would be to provide some sort of rule description or explanation, too. This would be cool for a few reasons:
 * It’s relevant documentation for the rule, so it makes sense for it to live alongside the rule
 * It helps clarify where the rule comes from, and what it’s aiming to check
 * It would make the job of the (or indeed any) validator a bit easier, since otherwise this information would need to be hardcoded in the validator

I mention this now just because it’s way easier to do this job as rules are being "discovered" in the docs and added, rather than retrospectively trying to reverse-engineer where each rule came from.

**Comment by samuele-mattiuzzo** [comment]
I won't triage this yet but instead I'll just leave this issue as is so we can keep this as a public-facing updates corner about this. Alas, valid suggestion and good idea logging its progress on Git straight away!
It's something we have in our agenda/todo list, to be tackled once the work is being planned alongside the validation team :)
