### ISSUE TITLE
[2.01] Context is wrong for some tests

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#126]
As [described in the SPEC](https://github.com/IATI/IATI-Rulesets/blob/version-2.01/SPEC.rst#iati-ruleset-spec), the `context` for a test is:

> […] used to select the XML elements that the contained rules will be tested against.

I guess it can be thought of as: _the thing that’s looped over_. So if you’re testing budgets, chances are the context should be `//iati-activity/budget` (which will test every budget) rather than `//iati-activity` (which will only test every activity – so behaviour for activities that contain multiple budgets might be unexpected).

[Here’s a concrete example](https://gist.githubusercontent.com/andylolz/0e18e29f7852b0fe2df6ac9c17e856a8/raw/cf3adcddf5764f208f8ccb946dab8456d8d55933/time_limit_bad_2.xml):
```xml
<iati-organisations><iati-organisation>
    <total-budget>
    	<period-start iso-date="2019-01-01"></period-start>
    	<period-end iso-date="2019-12-31"></period-end>
    </total-budget>
    <total-budget>
    	<period-start iso-date="2020-01-01"></period-start>
    	<period-end iso-date="9999-12-31"></period-end>
    </total-budget>
</iati-organisation></iati-organisations>
```

This `iati-organisation` contains two `total-budget`s. The first is less than 1 year in length, so that **should pass** the `time_limit` test. The second is several thousand years in length, which **should definitely fail** the `time_limit` test. But try running:

```sh
$ wget https://gist.githubusercontent.com/andylolz/0e18e29f7852b0fe2df6ac9c17e856a8/raw/cf3adcddf5764f208f8ccb946dab8456d8d55933/time_limit_bad_2.xml
$ python testrules.py rulesets/standard.json time_limit_bad_2.xml
```

…and you’ll see it doesn’t raise any issues. That’s because the test is applied per organisation, and the second budget is ignored. (Note that this is not a contrived example – `iati-organisation`s usually contain lots of `total-budget`s.)

**Comment by andylolz** [comment]
The `total-budget` example is fixed in #130, but _I think_ this issue still exists in some other places.

E.g. I think this rule probably has the same issue:
https://github.com/IATI/IATI-Rulesets/blob/fa8363222cd62bf743327eaa888764591bd7513c/rulesets/standard.json#L30-L38

And this rule:
https://github.com/IATI/IATI-Rulesets/blob/fa8363222cd62bf743327eaa888764591bd7513c/rulesets/standard.json#L47-L51

And these ones:
https://github.com/IATI/IATI-Rulesets/blob/fa8363222cd62bf743327eaa888764591bd7513c/rulesets/standard.json#L133-L138

Possibly others, too.

In the cases above, the problem occurs when an `iati-activity` (or `iati-organisation`) contains more than one `budget` (or `recipient-country-budget`, or `recipient-org-budget`, or `recipient-country-budget/budget-line`). It’s possible the test runner will say everything is fine, when in fact it has only checked the first example.

**Comment by andylolz** [comment]
Hmm… I think there are some other problems with that `between_dates` example.
 * `recipient-country-budget` is a child of `iati-organisation`, not `iati-activity`
 * `@value-date` is an attribute of `budget-line/value`, not `budget-line`

**Comment by Ocre42** [comment]
Noticed a few more errors when elements can have more than one occurrence and need to be evaluated under each one of them. While most of them can be sorted by changing the element being evaluated to the reoccurring one, that is not possible in some instances when the case to be evaluated is an attribute instead of a sub-element. 
The most notable example being `policy-marker`: when `@vocabulary=1` or `not(@vocabulary)` then `policy-marker/@significance` must exist, which must be evaluated for each `policy-marker` element. @samuele-mattiuzzo will be having a look at this.

**Comment by andylolz** [comment]
> The most notable example being `policy-marker`: when `@vocabulary=1` or `not(@vocabulary)` then `policy-marker/@significance` must exist, which must be evaluated for each `policy-marker` element.

@Ocre42 so I think the test in this case would be:

```json
{
    "///iati-activity/policy-marker": {
        "atleast_one": {
            "cases": [ {
                "condition": "@vocabulary='1' or not(@vocabulary)",
                "paths": [ "@significance" ]
             } ]
        }
    }
}
```

However, you are RIGHT that there is a bug that will prevent this from working! I think it’s just here:
https://github.com/IATI/IATI-Rulesets/blob/91113edc1211c5bd5f1e823ea5316287ff3d2a25/iatirulesets/__init__.py#L183

I think this line should instead say:

```python
        for element in tree.xpath(context_xpath):
```

**Comment by andylolz** [comment]
Aha – I sent \*this very fix\* to the `version-2.03` branch as part of #59, but the fix was not duplicated to other branches. See: d61d7a13.

**Comment by samuele-mattiuzzo** [comment]
thanks Andy

**Comment by andylolz** [comment]
This remains an issue for budget:

https://github.com/IATI/IATI-Rulesets/blob/8ed0cb4ece9b216f18dde0b64b50031f6c719e52/rulesets/standard.json#L40-L44

This will only test the first budget for an activity – it will ignore subsequent budgets. It should be:

```json
    "//iati-activity/budget": {
        "time_limit": {
            "cases": [
                { "start": "period-start/@iso-date", "end": "period-end/@iso-date" }
            ]
        }
    }
```
