### ISSUE TITLE
travis not running on version-2.02 branch

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#137]
Because `script:` on L11 is a bit indented:
https://github.com/IATI/IATI-Rulesets/blob/a76e95bbb3dd75ffeef5a27971530c3c0fd7f940/.travis.yml#L8-L11

**Comment by samuele-mattiuzzo** [comment]
weird, I can't see it on my machine, I just tried de-denting and re-indenting the line but git diff shows no changes

**Comment by andylolz** [comment]
> I just tried de-denting and re-indenting

L11 should have no indentation. Try opening the following in two tabs, and switching between them:
 * [tab 1](https://github.com/IATI/IATI-Rulesets/blob/version-2.01/.travis.yml#L11)
 * [tab 2](https://github.com/IATI/IATI-Rulesets/blob/version-2.02/.travis.yml#L11)

**Comment by samuele-mattiuzzo** [comment]
Yup, I see it now, I was on the wrong branch on my editor `2.01` for some reason as I read the issue as a 2.01 rather than 2.02 🤦‍♂️

**Comment by andylolz** [comment]
Looks good!
