### ISSUE TITLE
[2.03] Ensure percentages are a number between 0 and 100

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Rulesets#147]
Content must be a decimal number between 0 and 100 **inclusive**, with no percentage sign. Applicable to: 

- `iati-activities/iati-activity/recipient-country/@percentage`
- `iati-activities/iati-activity/recipient-region/@percentage`
- `iati-activities/iati-activity/sector/@percentage`
- `iati-activities/iati-activity/country-budget-items/budget-item/@percentage`
- `iati-activities/iati-activity/capital-spend/@percentage`

**Comment by samuele-mattiuzzo** [comment]
Work will start once #149 is reviewed
