### ISSUE TITLE
Suggestion: consider namespacing all contexts with `//iati-activity` or `//iati-organisation`

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#153]
So for instance, rather than:

```
//budget
```

…you could instead reference the same elements with:

```
//iati-activity/budget
```

Although it’s not strictly necessary to do this (since there’s currently no overlap between the element names in the two standards) it’s a bit more explicit, and also makes it possible to immediately determine to which standard a rule applies.

When testing a dataset, only the rules for the relevant standard need be applied (which can result in performance gains). This change makes that easy.

---

Alternatively, you could always provide absolute paths, which may well result in further performance gains.

**Comment by samuele-mattiuzzo** [comment]
Yeah, been thinking about absolute paths as well, deffo adding this issue to our general project improvement!

**Comment by andylolz** [comment]
I don’t think this is relevant given the new ruleset format. Closing
