### ISSUE TITLE
Feedback on newly implemented rules

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Rulesets#161]
Looks like we added a more comprehensive check for this element in 2.02 than in 2.01, including the if @ref not present, then @narrative must be included. Please could we add this into 2.01?

The ruleset rule is currently appearing in Provider org, ref, narrative, receiver org and ref. There is different wording for each. Should there be more consistency here?

**Comment by amy-silcock** [comment]
Tag element in 2.03 should also not contain a rule.

**Comment by amy-silcock** [comment]
2.03 budget element contains erroneous rules about country-budget-items

**Comment by samuele-mattiuzzo** [comment]
Hi @amy-silcock as a general rule, if these issues refer to more than one element we should make sure the issue's title reflect what's inside for clarity, hence why I have changed the issue title. Keep logging all of them as you see fit in this generic Feedback thread and then we can discuss and ticket them up separately tomorrow when you're back in the office

**Comment by amy-silcock** [comment]
Need to check rules present for result sub-elements in 2.03

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 when you get to review the related PRs, move this ticket along the project as well with them.

**Comment by akmiller01** [comment]
First item is resolved by rules 6.8.1, 6.9.1, 6.9.2, and 6.10.1.

No rules for tags, and I think the remaining feedback on budget-items and results have also been resolved.
