### ISSUE TITLE
Question about versioning?

### ISSUE THREAD

**Issue by rory09** [IATI/IATI-Rulesets#178]
My understanding was that rulesets are part of the standard and hence subject to version upgrades in the same way. However, I notice there's been a lot of activity recently which means that if a publisher was using rulesets to 'validate' their data in a manner of speaking, their data which was valid a few months ago (on v2.03) is no longer. This has cause some confusion with one of my clients, so I'd like to get some clarity.

This is particularly complicated if there are incorrect or overreaching rules which have been put into the official standard without versioning or review (see #177), as I'll now need to try to help the client decide which rules to implement and which to, essentially, ignore.

Any guidance would be appreciated - for now I'll be recommending the use of the ruleset as it was when 2.03 was released, but if there's a more 'official' recommendation, I'd be happy to advise that instead.

Happy to go into more detail over DMs or a call if that would be useful.

Thanks!

**Comment by samuele-mattiuzzo** [comment]
Hi @rory09 can you provide examples? I do understand the other related issue you raised, after taking a proper look yes, there is a bug there and you are correct in saying that by bundling `provider/receiver-org` under `iati-activity` we have enforced requiredness of either one of the two (while the rule is different) and it will be fixed.

For what concerns introducing rules in the Standard without a minor/major upgrade process (which I think is what you're suggesting happened) that is **NOT** the case at all.
