### ISSUE TITLE
Requirements fail with Python 3.7

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Rulesets#185]
I created a virtual environment using Python 3.7 as default, and was unable to install lxml due to the pinned version not supporting 3.7. Aside from looking at `travis.yml`, it isn't obvious which version of Python I should be using in order to successfully use this tool.

It'd be good to support as much of 3.x as we can by boosting lxml version to 4.3.3, and stating in the documentation which version of Python to use for the virtual environment.

**Comment by samuele-mattiuzzo** [comment]
Addressed with python 3 upgrades and merged
