### ISSUE TITLE
no-percent: the rule is enforced at Schema level, not needed in Ruleset

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#187]
https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L78-L92

This is already enforced by the Schema's [xsd:decimal](https://www.w3.org/TR/xmlschema-2/#decimal) type for those elements; we should remove the rule and the tests from the Ruleset

**Comment by samuele-mattiuzzo** [comment]
Relevant PRs:
- #195 
- #196 
- #197

**Comment by Ocre42** [comment]
Solved
