### ISSUE TITLE
If a result (baseline|target|actual) value is present, then it must be a number

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#189]
https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L139

https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L140

https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L141

We're checking for numeric values to be numbers in Ruleset but this should instead be enforced at Schema level. We should remove the rules from the Ruleset and the tests for them.

We should also update the Schema type in the relevant places ([example](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L1797) -> `xsd:string` to `xsd:decimal`)

**Comment by andylolz** [comment]
@samuele-mattiuzzo It seems like you might be working through [this gist](https://gist.github.com/andylolz/86630944e40d629e2098a49c0c501145), and creating issues. Is that the case?

**Comment by samuele-mattiuzzo** [comment]
we have made a copy of the gist and re-assessed some of the rules you pointed out yes.

I'm also logging issues without necessarily:
- having finalised all the discussions around them with the team
- having tagged all the correct versions they need fixing on

**Comment by andylolz** [comment]
Great! I didn’t hear anything back regarding the gist, so I wasn’t sure whether you’d looked at it. Great to hear you are going through the points 👍

**Comment by samuele-mattiuzzo** [comment]
Yeah sorry about the silence, but like I said, hectic times :D I forked your gist and used it as a base for our investigations, we also needed to decide whether the effort and time used to fix them was worth it or we should have instead backtracked to pre-January

We learned a bit more about Ruleset, Standard and how to read them through those January changes, so we kept them and decided to fix them. Some are straight forward, some still require some back and forth discussions (eg, this one, as it changes a Schema type effectively enforcing the `must be omitted` part as a side effect, sort of, so it's sort of sensitive).

Your gist is invaluable btw!

**Comment by samuele-mattiuzzo** [comment]
How this will be changed (@amy-silcock to :+1: / 👎 )

- we cannot change the `Schema` because it would prevent `2.02` data from passing `2.03` validation; the `number` type requiredness is also a *should* and not a *must*, one more reason to retain `xsd:string` as the base type

- instead of checking for the existance of the elements in the `if` clause, we should check whether `result/indicator/@measure` is present and has a value `!= 5` (as per this [Indicator Measure Codelist](http://reference.iatistandard.org/203/codelists/IndicatorMeasure/)), so that we can retain the checks under the `then` clause.

**Comment by samuele-mattiuzzo** [comment]
Relevant PR #204

**Comment by amy-silcock** [comment]
Details of the issue and how we propose to fix it can be found here: https://discuss.iatistandard.org/t/bug-fix-the-new-2-03-result-baseline-and-period-value-rules-are-not-backwards-compatible/1731
