### ISSUE TITLE
If sector for vocabulary 98 or 99 is specified, then the narrative should exist

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#191]
https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L138

We should be checking for the same sector codes when we check for the narrative as well

**Comment by samuele-mattiuzzo** [comment]
Relevant PRs:

- #205 
- #206 
- #207

**Comment by Ocre42** [comment]
Merged and solved
