### ISSUE TITLE
If a default currency is not specified, then there must be at least one crs-add/loan-status currency

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#192]
https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L136

This is probably a duplicate of [a similar rule](https://github.com/IATI/IATI-Rulesets/blob/b88c627bc91e4e6c70a8a0cc6f2541503ec282e4/rulesets/standard.json#L169) and requires further investigations before addressing

**Comment by samuele-mattiuzzo** [comment]
Relevant PRs:

- #208 
- #209 
- #210

**Comment by Ocre42** [comment]
Merged and solved
