### ISSUE TITLE
Unclear whether 'before' references ordering or chronology

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Rulesets#26]
Elements such as [activity-date](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/activity-date/) have attributes that indicate ordering. These are checked through rulesets, and output on the documentation pages.

The text specifying that one data must be before the other is defined at https://github.com/IATI/IATI-Rulesets/blob/61cff20f39cf2a59d3b2a6a99c33c2bbf7bf87c6/iatirulesets/text.py#L44 The output this generates is unclear whether one element must be before the other chronologically or in terms of physical order in the XML.

As such, the text should be updated to ` must be chronologically before `.

**Comment by andylolz** [comment]
Or “earlier than”?

Though I think I prefer chronologically before…

**Comment by hayfield** [comment]
`earlier than` has a similar problem to `before` in that it could refer to being earlier in the document (though were this relating to times, particularly if they were both within a single calendar day, rather than dates it'd work a fair bit better).
