### ISSUE TITLE
Complete List of IATI Validator Messages

### ISSUE THREAD

**Issue by sriza** [IATI/IATI-Rulesets#261]
We are currently working on IATI Publisher and were looking for the list of probable validation messages ( error, critical, success, and warning) that the IATI validator responds with. Following are the CSV files we found:

- https://github.com/IATI/js-validator-api/blob/develop/docs/data-quality-rules.csv
- https://github.com/IATI/IATI-Rulesets/blob/xslt-rules/docs/data-quality-rules.csv 

We couldn't find critical messages and success messages in them. Could you please verify if these are correct materials to take reference from?
Also, could you please let us know if there are other sources containing the complete list of validation messages?

Thank you

**Comment by nosvalds** [comment]
Hi @sriza 

This is the best source for the messages that are controlled by IATI:
https://github.com/IATI/validator-rule-tracker

The full content of the "Critical" errors messages are controlled by the library we use for XML parsing and schema validation which is [libxml2](https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home).

Example of one:
https://github.com/GNOME/libxml2/blob/202b8e1954af9703a453e6891c2a6cccc1a8df4f/HTMLparser.c#L1523

-Nik
