### ISSUE TITLE
`date_order` Rule should treat equal `less` and `more` values as passing

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Rulesets#41]
Following the discussion in #36...

It has been agreed that the `date_order` Rule should act as passing when the `less` and `more` values are the same. This means that the current situation that states otherwise is a bug. Since the change is backwards-compatible, it will be rectified as a bug fix following the [Minor Changes](http://iatistandard.org/202/upgrades/#open-consultation-on-all-proposed-changes) procedure.

This will require changes to:

* The Ruleset spec (IATI-Rulesets/SPEC.rst - v1.04+)
* The copy on the IATI website (IATI-Rulesets/iatirulesets/text.py - see #36, #37, #38, #39 - v1.04+)
* pyIATI (iati.core/iati/core/tests/test_rulesets.py, iati.core/iati/core/rulesets.py - feature branch)

**Comment by hayfield** [comment]
`IATI-Rulesets` has been updated, PRs to update SSOT modules created.

**Comment by andylolz** [comment]
Great – I think this also means #40 is fixed.
