### ISSUE TITLE
"sum" rule is missing from iatistandard.org

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Rulesets#46]
https://github.com/IATI/IATI-Rulesets/blob/version-2.02/rulesets/standard.json#L23-L28
vs
http://iatistandard.org/202/rulesets/standard-ruleset/#non-machine-readable-rules

**Comment by hayfield** [comment]
Resolved for 2.02 in https://github.com/IATI/IATI-Standard-SSOT/pull/110 (should be deployed today) / fix already deployed for 2.01.

**Comment by andylolz** [comment]
>  * The sum of values matched at `recipient-country/@percentage` and `recipient-region/@percentage` must be 100.
>  * The sum of values matched at `recipient-region/@percentage` and `recipient-country/@percentage` must be 100.

Why is the rule listed twice? I think #47 should fix this.
