### ISSUE TITLE
Add rules (no more than one): reference element

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Rulesets#48]
Update rule for reference element to read:

>The reference element MUST ONLY be reported once. Either here OR at result level.

**Rules to add**

- [x] No More than One
    - [x] `iati-activities/iati-activity/result/reference`
    - [x] `iati-activities/iati-activity/result/indicator/reference`

**Base XPath**

- [x] `iati-activities/iati-activity/result/indicator/`

This level needs to be used due to `1..*` relationship between results and indicators.

**Paths**

- [x] `reference`
- [x] `../reference`

**Comment by allthatilk** [comment]
Issue may not be needed but spreadsheet inconsistent. Clarification @dalepotter @hayfield ?

**Comment by dalepotter** [comment]
To clarify, this issue appears to relate to `iati-activities/iati-activity/result/reference` and `iati-activities/iati-activity/result/indicator/reference`.
