### ISSUE TITLE
Add rules (regex matches): ref attributes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Rulesets#50]
> If this is not present then the narrative MUST contain the name of the organisation (read: there is content). - REGEX

**Impacted attributes:**

- [x] `iati-activities/iati-activity/planned-disbursement/provider-org/@ref`
- [x] `iati-activities/iati-activity/planned-disbursement/receiver-org/@ref`
- [x] `iati-activities/iati-activity/transaction/provider-org/@ref`
- [x] `iati-activities/iati-activity/transaction/receiver-org/@ref`
- [x] `iati-organisations/iati-organisation/recipient-org-budget/recipient-org/@ref`

Regex for non-space character: `^(?!\s*$).+` ([source](https://stackoverflow.com/a/3085553))

Logic:

```
if @ref is not present:  # condition
    narrative.text() matches ^(?!\s*$).+
```

**Comment by andylolz** [comment]
I can’t figure out which proposal this refers to.

Separately: I’m unsure why you’d use a negative lookahead here… Wouldn’t the following do the trick?

```regex
^\s*\S
```

I.e. from the start of the string, zero or more whitespace characters followed by a non-whitespace character.

**Comment by hayfield** [comment]
> I can’t for the life of me figure out which proposal this refers to.

This is from the description of the attribute, as quoted at the start of this PR. We cannot check whether the value actually is the name of the organisation. What we can do, however, is check the minimum requirement for the name of an organisation (that there is at least one non-whitespace character).

> But also: I’m unsure why you’d use a negative lookahead here

Because it was the top response on Stackoverflow for this (I was working on the assumption that the might of the internet was more powerful than my regex skills... though on hindsight this probably isn't the problem to look for the internet's wisdom on since it's such a simple thing that people asking the question probably aren't going to be the ones that can fully assess the best solution!).

Your suggestion is definitely nicer. Will create another PR to change the regex.

**Comment by andylolz** [comment]
> This is from the description of the attribute, as quoted at the start of this PR.

Could you provide a link? I’m struggling to find the related proposal.

> Your suggestion is definitely nicer. Will create another PR to change the regex.

Great! Thanks!

**Comment by hayfield** [comment]
@IATI/bas

**Comment by hayfield** [comment]
Without spending too much time looking... the Rule already exists at 2.02, though not in a Ruleset form. The attribute descriptions were being clarified with 2.03 so the opportunity has been taken to codify the Rule in a Ruleset. This could possibly be backported to previous versions, though has not been at this stage.

@IATI/bas could you provide a link to confirm?

**Comment by amy-silcock** [comment]
We were updating the @ref description to align with the migration to Org-ID.guide: https://discuss.iatistandard.org/t/migration-of-organisationregistrationagency-codelist-to-org-id-guide-included-2-03/851/11

**Comment by hayfield** [comment]
As noted in #67:

A regex to represent a string containing some non-whitespace character cannot be represented in JSON due to the way backslashes are handled across each regex and JSON.

As such, this Rule is being removed from the set of Machine Actionable Rules since, well, it's not Machine Actionable within the current format!

**Comment by andylolz** [comment]
> A regex to represent a string containing some non-whitespace character cannot be represented in JSON due to the way backslashes are handled across each regex and JSON.
> 
> As such, this Rule is being removed from the set of Machine Actionable Rules since, well, it's not Machine Actionable within the current format!

^^ I don’t think that’s correct, is it? See #60 for a demonstration that it’s possible to do this in JSON.

**Comment by andylolz** [comment]
#60 includes tests that use `\\S`. The [green tick](https://travis-ci.org/IATI/IATI-Rulesets/builds/338040316) demonstrates it works.

**Comment by andylolz** [comment]
In terms of what’s possible to do in JSON: The [github syntax highlighting in this comment](https://github.com/IATI/IATI-Rulesets/pull/58#discussion_r166113307) illustrates it nicely.

**Comment by dalepotter** [comment]
So just looking at this one again to refresh my mind on what the json+regex issue was and why the tests in #60 passed when I would have expected them to fail.

So it seems that my approach to creating a minimal test case using `json.loads('{"regex": "\\S"}')` was incorrect given how requests and json actually encode an [equivalent file](https://pastebin.com/raw/kx54jGKQ), for example using: 

```
>>> requests.get("https://pastebin.com/raw/kx54jGKQ").text
>>> json_str
'{"regex": "\\\\S"}'
>>> json.loads(json_str)
{'regex': '\\S'}
```

Having cleared that one up, #60 would be a good addition although we're reluctant to make this the first official use of the `condition`, given there is [confusion about how this is meant to be used](https://github.com/IATI/IATI-Rulesets/pull/59#issuecomment-363393535) (albeit this is partially resolved in #64 - thanks for that one).

At this stage in the v2.03 process (we have a hard deadline to get 2.03 live by Monday), there won't be enough time to fully get to the bottom of this, though we are keen to fully clarify and make consistent/fix the use of `condition` in the near future. In the first instance I've added the issue to our internal issue log for discussion on the way forward on Monday.

**Comment by andylolz** [comment]
> #60 would be a good addition

I actually agree with @hayfield that it doesn't _really_ check anything super useful. I don’t mind if it’s not included – I just wanted to be clear about the reasoning for it (i.e. I don’t think it’s due to a technical issue).

> we have a hard deadline to get 2.03 live by Monday

Okay wow so you have a bunch of work on, I guess… Well, I’ve updated the descriptions for #59 and #62, to clarify that they should be addressed before merging to `version2.03` (either by merging them or by reverting the PRs they reference.)

**Comment by andylolz** [comment]
> we have a hard deadline to get 2.03 live by Monday

I should add I was quite surprised to read this! I thought this was the reference for this information:
http://iatistandard.org/202/upgrades/decimal-upgrade-to-2-03/#upgrade-timetable
