### ISSUE TITLE
Add rules: result @value presence - qualitative

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Rulesets#52]
Attributes of interest:

- [x] `iati-activities/iati-activity/result/indicator/baseline/@value`
- [x] `iati-activities/iati-activity/result/indicator/period/target/@value`
- [x] `iati-activities/iati-activity/result/indicator/period/actual/@value`

> The @value must be omitted for qualitative measures

There is no type of Rule to directly state that there must be zero of something. As such, this Rule is currently Non-Machine Readable.

**Comment by hayfield** [comment]
Related to other Rule, see #51

**Comment by hayfield** [comment]
IATI/IATI-Schemas#353

**Comment by hayfield** [comment]
This will likely go in https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/rulesets/standard-ruleset.rst

@IATI/bas or @dalepotter can you confirm that this is the correct location?

**Comment by dalepotter** [comment]
I believe that this should indeed go in https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/rulesets/standard-ruleset.rst AND listed as a rule on the reference pages for the attributes. 

The way that I believe we achieve the latter is to include it as part of the definition.

Perhaps @IATI/bas could confirm this though?

**Comment by amy-silcock** [comment]
I agree with Dale.

From a quick glance, the current non-machine readable rules are written differently on the extra documentation page to those on the reference pages. Is there a reason for this?
