### ISSUE TITLE
Create more generic `count` Rule

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Rulesets#53]
As noted in #52, it is currently possible to specify a Machine Readable Rule to check for occurrences `0..1` (no more than one) and `1..*` (at least one).
#52 requires that an occurrence `0` is checked. This is not currently possible.

Rather than adding another specific case, a more generic Rule should be created.

---

Potential names: `count` or `instances` or `instance_count` or something else similar.
Attribute for rule: `count` (similar to XPath function) or `instances`
Values for attributes: a generic manner for specifying ranges. For example: `0`, `1`, `0..1`, `0..*`, `1,3,7`, `1<`, `<5`, `0..4,7..9,14`, `<=4`, `2<=`

**Comment by samuele-mattiuzzo** [comment]
To be triaged and evaluated after this sprint ends
