### ISSUE TITLE
schemadoc.py and meta_tests.py are unused. remove.

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#63]
I’m not sure what [schemadoc.py](https://github.com/IATI/IATI-Rulesets/blob/c33d11885e1084bb99d897c9a5dc3bfcea91c0fb/schemadoc.py) is for… It looks like it might be cruft. It’s certainly out of sync with [SPEC.rst](https://github.com/IATI/IATI-Rulesets/blob/77d5f95de3ec7504e2cfd1f8a770adb8e2ea9f27/SPEC.rst), which appears to be canonical (e.g. it looks like that’s what [the SSOT docs generator uses](https://github.com/IATI/IATI-Standard-SSOT/blob/489550d53cd3b7c8aa16c3b52a68f66f6dba53b1/gen_rst.sh#L17).

If that’s the case, schemadoc.py should be removed to avoid confusion.

**Comment by Ocre42** [comment]
We will be evaluating this during the next week.

**Comment by andylolz** [comment]
Cool – thanks. meta_tests.py looks like cruft to me, too.
