### ISSUE TITLE
Add a rule to check iati-activity/iati-identifier starts with org ID

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#72]
The [v2.0x `iati-activity/iati-identifier` definition](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition) says:

> […]
> This MUST be prefixed with EITHER the current IATI organisation identifier for the reporting organisation (`reporting-org/@ref`) OR a previous identifier reported in `other-identifier`, and suffixed with the organisation’s own activity identifier. The prefix and the suffix should be separated by a hyphen “-”.

It ought to be possible to check this programmatically (in fact, the PWYF Aid Transparency Tracker does this).

**Comment by andylolz** [comment]
This refs #13. Specifically:

>  - [x] The identifier MUST be the prefix to the iati-identifier

I’m not sure why this box is checked… It doesn’t look like there was ever a test for this… But in any case it’s not quite right, since `other-identifier/@ref` may be used as the prefix.

**Comment by akmiller01** [comment]
Covered by 1.1.12 now: https://github.com/IATI/IATI-Rulesets/blob/version-2.03/rulesets/standard.json#L29
