### ISSUE TITLE
SPEC definition of `regex_matches` / `regex_no_matches` is probably not quite right

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#75]
> **regex_matches**
>     Keys: ``condition``, ``paths``, ``regex``
> 
>     The provided ``regex`` must match the text of all elements matched by ``paths``
> 
> **regex_no_matches**
>     Keys: ``condition``, ``paths``, ``regex``
> 
>     The provided ``regex`` must match the text of none of the elements matched by ``paths``

This wording could probably do with clarifying:

 * the test for each of the `paths` is independent. So I think I’d say “the text of each element” rather than “the text of all elements”.
 * in PHP, “match” means something more like python’s `search`. So I’m not sure if I’d say “match the text”. I’m not exactly sure how I’d reword it, though.

This second point relates to #25.

**Comment by hayfield** [comment]
> in PHP, “match” means something more like python’s search

It's stated elsewhere in the SPEC that these are PERL-style regular expressions, as such the behaviour is as per that... which as far as a reading of the internet indicates is the behaviour of `search` in Python (it's not implicitly anchored at the start of the string).

**Comment by andylolz** [comment]
Yeah, I think I made this point badly – I was thinking about the meaning in English, which I didn’t really explain here. Maybe this is better:

> In perl, “match” doesn’t mean the same thing as we’d typically understand by “match” in English (i.e. I think I’d assume a complete match i.e. `'/^{}$/'`).

But look, there are definitely more important things to fix. Happy for this to be closed.
