### ISSUE TITLE
[2.01] Add rule: budget period can't be over a year in length

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Rulesets#85]
The start-date and end-date for budgets must not be more than one year: `budget/period-start` - `budget/period-end` < 1 year

**Comment by samuele-mattiuzzo** [comment]
Thank you @andylolz we will ask Amy tomorrow morning to provide you with the information needed.

**Comment by andylolz** [comment]
Cool – thanks. It’s just useful for reference, you know. No doubt it’s there somewhere.

**Comment by andylolz** [comment]
> Thank you @andylolz we will ask Amy tomorrow morning to provide you with the information needed.

Never mind – please consider this part of #121.

**Comment by samuele-mattiuzzo** [comment]
`github set-reminder` is a much needed feature 🤦‍♂️  sorry I totally forgot, my bad :(

Ping this issue again in the morning, at least a reference to that rule is due (regardless of #121 )

**Comment by andylolz** [comment]
I guess I found it – the various [*budget/period-end](http://reference.iatistandard.org/201/activity-standard/iati-activities/iati-activity/budget/period-end/) pages say:

> The end of the period (**which must not be greater than one year**)

That said, [the budget overview page](http://reference.iatistandard.org/201/activity-standard/overview/budgets/) says:

> It is possible to report periods other than years, but this is not recommended.

So something’s not quite right there.

In any case, that seems like a perfectly good reference for the rule.

**Comment by amy-silcock** [comment]
My understanding is that the rule in v2x is:
![image](https://user-images.githubusercontent.com/27764077/52405821-1f624000-2ac4-11e9-95a3-4da69f33203b.png)

This doesn't stop an organisation publishing budgets for less than a year e.g. 6 months. Hence the comment in the overpages. We're looking to re-write those later this year and ensure they're consistent with the schema.

We only use rules found in the schema for creating the rulesets.

**Comment by andylolz** [comment]
> This doesn't stop an organisation publishing budgets for less than a year e.g. 6 months. Hence the comment in the overpages

Oh I seeeeeee. I took that wording to mean periods **longer than a year** were not recommended.

(Separately – I didn’t realise IATI discourages budgets shorter than a year – I’m very surprised to learn that, especially given the aid transparency index rewards quarterly budgets.)

**Comment by amy-silcock** [comment]
That guidance was written before my time..... And probs needs to be updated in line with what data users find more helpful?

**Comment by andylolz** [comment]
> And probs needs to be updated in line with what data users find more helpful?

^^ Agreed! Big +1 for that.

Apologies for derailing this issue so much! Thanks all for your patience.
