### ISSUE TITLE
[2.01] Add rule: positive decimal in specific elements

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Rulesets#86]
The elements in the following list should enforce a positive decimal

```
iati-activities/iati-activity/recipient-country/@percentage
iati-activities/iati-activity/recipient-region/@percentage
iati-activities/iati-activity/sector/@percentage
iati-activities/iati-activity/capital-spend/@percentage
```

Add the relevant rule and tests

**Comment by amy-silcock** [comment]
Note that the wording is different for:

`iati-activities/iati-activity/country-budget-items/budget-item/@percentage`

**Comment by samuele-mattiuzzo** [comment]
That part is probably being checked in #83
