### ISSUE TITLE
[2.01] Add rule: if "condition" then "element" must exist

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Rulesets#89]
Applicable for:

- if not `other-identifier/owner-org/@ref` then `iati-activities/iati-activity/other-identifier/owner-org/narrative` MUST exist
- if `iati-activities/iati-activity/sector/@vocabulary` is (98 OR 99) then `iati-activities/iati-activity/sector/narrative` MUST exist
- if `iati-activities/iati-activity/policy-marker` then `iati-activities/iati-activity/policy-marker/@significance` MUST exist
- if `policy-marker/vocabulary` is "99-RO" then `iati-activities/iati-activity/policy-marker/narrative` MUST exist
- if not `provider-org/ref` then `iati-activities/iati-activity/transaction/provider-org/narrative` MUST exist
- if not `iati-activity/default-currency` then `iati-activities/iati-activity/crs-add/loan-status/@currency` MUST exist
- if not `receiver-org/ref` then `iati-activities/iati-activity/transaction/receiver-org/narrative` MUST exist

**Comment by amy-silcock** [comment]
To add: 
if not `iati-activities/iati-activity/participating-org/@ref` then `iati-activities/iati-activity/participating-org/narrative` MUST exist

**Comment by amy-silcock** [comment]
* if `policy-marker/vocabulary` is "99-RO" then `iati-activities/iati-activity/policy-marker/narrative` MUST exist

This is not complete? The narrative MUST ONLY exist when code 99 is used.

**Comment by amy-silcock** [comment]
Does this need to be a rule?
 * if `iati-activities/iati-activity/policy-marker` then `iati-activities/iati-activity/policy-marker/@significance` MUST exist

As it's mandated by the occurrence in the schema?

**Comment by amy-silcock** [comment]
Is not 

* if not `iati-activity/default-currency` then `iati-activities/iati-activity/crs-add/loan-status/@currency` MUST exist 

covered by: https://github.com/IATI/IATI-Rulesets/issues/87 ?

**Comment by amy-silcock** [comment]
For the budget-item element, should there be something like:

* if multiple `iati-activities/iati-activity/country-budget-items/budget-item` then `iati-activities/iati-activity/country-budget-items/budget-item/@percentage` MUST exist?

Or does this follow similar rules as to reporting multiple sectors and should be put there?
